server:
  port: 8081
  context-path: /gzxant/web

spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8

sitemesh:
  contentPath: /*
  decoratorPath: classpath:/layouts/default.jsp
  excludedPaths: /js/*,/assets/*,/css/*

management:
  security:
    enabled: false

logging.level.project.user.UserClient: DEBUG

mybatis:
  mapper-locations: classpath:mapper/sys/**/*.xml, classpath:mapper/log/**/*.xml
  type-aliases-package: com.gzxant.entity
mybatis-plus:
  mapper-locations: classpath:mapper/sys/**/*.xml, classpath:mapper/log/**/*.xml
  type-aliases-package: com.gzxant.entity
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
    metaObjectHandler: com.gzxant.config.plus.SysMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

security:
  basic:
    enabled: false
